plugins:
  pkv_news_tag:
    client: true
    default: "news"
  pkv_community_link:
    client: true
    default: "/"
  pkv_parkour_info_link:
    client: true
    default: "/"
  pkv_learn_parkour_link:
    client: true
    default: "/"
