plugins:
  pavilion_home_site_title:
    client: true
    default: "Hey, We're Pavilion."
  pavilion_home_site_description:
    client: true
    default: "We're a freelancer cooperative that works exclusively with <a href='https://discourse.org' class='animated-link' target='_blank'>Discourse</a>."
  pavilion_team_group:
    type: group
    default: "members"
    client: true
  pavilion_unassigned_tags:
    type: tag_list
    default: "dev-needed"
  max_earnings_target_month:
    default: 5000
  max_actual_hours_target_month:
    default: 240